# Generated by Django 6.0.4 on 2026-06-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_linked_patient_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_reminders_appointments',
            field=models.BooleanField(default=True, verbose_name='lembretes de consulta por e-mail'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_reminders_journey',
            field=models.BooleanField(default=True, verbose_name='atualizações da jornada por e-mail'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_reminders_maya',
            field=models.BooleanField(default=False, verbose_name='resumos da Maya por e-mail'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='nome do contato de emergência'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='telefone do contato de emergência'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='user',
            name='reminder_frequency',
            field=models.CharField(choices=[('on_update', 'Apenas quando houver novidade'), ('daily', 'Diariamente'), ('weekly', 'Semanalmente')], default='on_update', max_length=20, verbose_name='frequência dos lembretes'),
        ),
    ]
