# Generated by Django 6.0.4 on 2026-06-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='notificações web ativas'),
        ),
    ]
