# Generated by Django 5.2.11 on 2026-05-19 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('psychology', 'Psicologia'), ('nutrition', 'Nutricao'), ('acupuncture', 'Acupuntura'), ('physiotherapy', 'Fisioterapia'), ('wellbeing', 'Bem-estar')], max_length=30)),
                ('specialty', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=260)),
                ('tags', models.CharField(blank=True, help_text='Separe por virgulas.', max_length=180)),
                ('contact_label', models.CharField(default='Entrar em contato', max_length=80)),
                ('contact_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'parceiro multidisciplinar',
                'verbose_name_plural': 'parceiros multidisciplinares',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('treatment', 'Tratamento'), ('routine', 'Rotina'), ('feelings', 'Acolhimento'), ('hope', 'Esperanca')], default='feelings', max_length=20)),
                ('body', models.TextField(max_length=900)),
                ('pseudonym', models.CharField(default='Paciente AMARE', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('moderation_note', models.CharField(blank=True, max_length=220)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'relato da comunidade',
                'verbose_name_plural': 'relatos da comunidade',
                'ordering': ['-approved_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('notes', models.CharField(blank=True, max_length=220)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluida')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='personal_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarefa pessoal',
                'verbose_name_plural': 'tarefas pessoais',
                'ordering': ['status', 'due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Laudo pos-tratamento', max_length=120)),
                ('file', models.FileField(blank=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('locked', 'Bloqueado'), ('available', 'Liberado')], default='locked', max_length=20)),
                ('release_note', models.CharField(blank=True, max_length=220)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'laudo de tratamento',
                'verbose_name_plural': 'laudos de tratamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('support', 'Apoio')], default='support', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.communitypost')),
            ],
            options={
                'verbose_name': 'reacao da comunidade',
                'verbose_name_plural': 'reacoes da comunidade',
                'constraints': [models.UniqueConstraint(fields=('post', 'patient'), name='unique_community_reaction_per_patient')],
            },
        ),
    ]
