# Generated by Django 6.0.4 on 2026-05-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('emotional', 'Apoio emocional'), ('fertility', 'Fertilidade'), ('routine', 'Rotina'), ('family', 'Familia e rede'), ('wellbeing', 'Bem-estar')], max_length=30)),
                ('audience', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=320)),
                ('support_type', models.CharField(max_length=120)),
                ('contact_label', models.CharField(default='Acessar comunidade', max_length=80)),
                ('contact_url', models.URLField()),
                ('tags', models.CharField(blank=True, help_text='Separe por virgulas.', max_length=180)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'comunidade de apoio',
                'verbose_name_plural': 'comunidades de apoio',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
