# Generated by Django 6.0.4 on 2026-06-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fix_community_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcommunity',
            name='tags',
            field=models.CharField(blank=True, help_text='Separe por vírgulas.', max_length=180),
        ),
    ]
