# Generated by Django 6.0.4 on 2026-04-20 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmentstep',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='treatments.treatment'),
        ),
        migrations.AddConstraint(
            model_name='treatment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient',), name='unique_active_treatment_per_patient'),
        ),
        migrations.AddConstraint(
            model_name='treatmentstep',
            constraint=models.UniqueConstraint(fields=('treatment', 'order'), name='unique_treatment_step_order'),
        ),
    ]
