# Generated by Django 6.0.4 on 2026-05-30 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('week', models.PositiveSmallIntegerField()),
                ('uploaded_at', models.DateTimeField()),
                ('size_label', models.CharField(max_length=24)),
                ('file', models.FileField(upload_to='journey_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='treatments.treatment')),
            ],
            options={
                'verbose_name': 'documento da jornada',
                'verbose_name_plural': 'documentos da jornada',
                'ordering': ['week', 'uploaded_at', 'name'],
            },
        ),
    ]
