# Generated by Django 6.0.4 on 2026-05-30 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_journeydocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('step', models.PositiveSmallIntegerField()),
                ('video_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, upload_to='journey_videos/')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('thumbnail_file', models.FileField(blank=True, upload_to='journey_video_thumbnails/')),
                ('duration', models.CharField(blank=True, max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'video da jornada',
                'verbose_name_plural': 'videos da jornada',
                'ordering': ['step', 'title'],
            },
        ),
    ]
