# Generated by Django 6.0.4 on 2026-04-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('consultation', 'Consulta'), ('exam', 'Exame')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('details', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'compromisso',
                'verbose_name_plural': 'compromissos',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
