# Generated by Django 6.0.4 on 2026-04-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('mode', models.CharField(choices=[('llm', 'LLM'), ('fallback', 'Fallback')], default='fallback', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'interação com a Maya',
                'verbose_name_plural': 'interações com a Maya',
                'ordering': ['-created_at'],
            },
        ),
    ]
