# Generated by Django 6.0.4 on 2026-04-20 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiinteraction',
            options={'ordering': ['-created_at'], 'verbose_name': 'interacao com a Maya', 'verbose_name_plural': 'interacoes com a Maya'},
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='intent',
            field=models.CharField(choices=[('treatment', 'Tratamento'), ('routine', 'Rotina'), ('feelings', 'Acolhimento'), ('symptom', 'Sintoma'), ('general', 'Geral')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Baixo'), ('medium', 'Medio'), ('high', 'Alto')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='suggested_next_step',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.CreateModel(
            name='MayaConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('treatment', 'Meu tratamento'), ('routine', 'Minha rotina'), ('feelings', 'Como estou me sentindo')], max_length=20)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=220)),
                ('starter_prompt', models.CharField(max_length=180)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maya_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversa da Maya',
                'verbose_name_plural': 'conversas da Maya',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='assistant.mayaconversation'),
        ),
        migrations.AddConstraint(
            model_name='mayaconversation',
            constraint=models.UniqueConstraint(fields=('user', 'kind'), name='unique_maya_conversation_per_user_kind'),
        ),
    ]
